### ISSUE TITLE
V icons is braking - desktop

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bariatric-Site#12]
On desktop version, the V sines are braking. 
Mobile version is fine. 

Tested on FF IE and chrome. 
URL: http://bariatric.co.il/

![image](https://user-images.githubusercontent.com/26923359/36088055-30600c18-0fde-11e8-99de-d4f8a5a9c96f.png)

**Comment by MeanEYE** [comment]
This check mark is set as background image but there's no `background-size` set.
