### ISSUE TITLE
Video autoplay enable

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bariatric-Site#14]
When clicking the youtube button it opens a lightbox with the video inside.
That video should start automatically

Youtube button:
![image](https://user-images.githubusercontent.com/26923359/36246269-9d64d73e-1237-11e8-9a81-635e9dfe7c3c.png)

The lightbox with the video that should start automatically: 
![image](https://user-images.githubusercontent.com/26923359/36246294-c33cf2f2-1237-11e8-9390-673c6acf4466.png)

**Comment by MeanEYE** [comment]
Video should play once dialog opens.
