### ISSUE TITLE
Add language menu 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bariatric-Site#6]
Language menu ready in drive. 
 

_Sent from my Samsung SM-J710F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MeanEYE** [comment]
@iliyaM site already has Arabic language created. All it needs is language menu to switch between them.

**Comment by iliyaM** [comment]
Waiting for git revert on this site.
