### ISSUE TITLE
Final Adding Arabic content  

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bariatric-Site#7]
Add Arabic content.
Content guide in Iliya's e mail.

Content changes that client have no access from backend.  

_Sent from my Samsung SM-J710F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by iliyaM** [comment]
@talovdat 
reopen when final content arrives

**Comment by talovdat** [comment]
Final content in Iliya's e mail.
Please reopen issue.

**Comment by MeanEYE** [comment]
@iliyaM is this done?
