### ISSUE TITLE
Test CRM and email.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Bariatric-Site#9]
I've upgraded the site and configured everything properly however I need to make sure everything works from the old site:

- [x] Facebook integration;
- [x] Google Tag Manager;
- [x] Mailing through SendGrid.

**Comment by MeanEYE** [comment]
Forgot to mention that you can tick checkboxes I've made!

**Comment by eyalway2cu** [comment]
Went through all items and they are ok. The only issue is Callbox module, it is active but not actively showing code on site.

**Comment by MeanEYE** [comment]
Five days later, sort of late.
But I am looking into it now. Don't add through GTM.

**Comment by eyalway2cu** [comment]
Please tag me next time, I am getting a ton of Github email notifications and do not always look since most are irrelevant to me.

**Comment by MeanEYE** [comment]
You are tagged, subscribed and assigned. This and 5 other issues which you didn't bother to look. Next step is hitting you on the head.

**Comment by MeanEYE** [comment]
Configure it then. There's detailed configuration on what to receive. Make it so you receive assignment and mentions. Not everything.
